In [5]:
import numpy as np 
import numpy.linalg as la 


In [7]:

def PageRank(A, niter):

    M = np.zeros_like(A)

    for i in range(M.shape[1]):
        if (np.sum(A[:, i]) != 0):
            M[:, i] = A[:, i] / np.sum(A[:, i])
        else:
            M[:, i] = 1 / len(A[:, i])
    
    G = (0.85 * M) + ((0.15/M.shape[0]) * np.ones_like(M))
    x = np.zeros(M.shape[0])
    x[0]= 1

    for i in range(niter):
        x = G @ x
        x = x/la.norm(x,1)
    return x



In [14]:
small_connected_idx = np.array([4, 9, 3, 2, 1])
small_connected = np.array([[0, 0.25, 0, 0, 0],
                            [1, 0, 1/3, 1/3, 1/3],
                            [0, 0.25, 0, 1/3, 1/3],
                            [0, 0.25, 1/3, 0, 1/3],
                            [0, 0.25, 1/3, 1/3, 0]])
print(small_connected_idx)
print(PageRank(small_connected, 1000))

[4 9 3 2 1]
[0.09036188 0.28405589 0.20852741 0.20852741 0.20852741]


In [16]:
small_disconnected = np.array([[0, 0.5, 0.5, 0, 0, 0 ],
                               [0.5, 0, 0.5, 0, 0, 0 ],
                               [0.5, 0.5, 0, 0, 0, 0 ],
                               [0, 0, 0, 0, 0.5, 0.5 ],
                               [0, 0, 0, 0.5, 0, 0.5 ],
                               [0, 0, 0, 0.5, 0.5, 0 ]])
small_disconnected_idx = np.array([6,5,4,3,2,1])

print(small_disconnected_idx)
print(PageRank(small_disconnected, 1000))


[6 5 4 3 2 1]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
